### PR TITLE
Adding documentation on migrating to M-Lab fast tables

### PR DESCRIPTION
**Pull request by mtlynch**
[Review on Reviewable](https://reviewable.io/reviews/m-lab/mlab-wikis/49)

### CODE REVIEW

**Comment by georgiamoon** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[MigratingToFastTables.md, line 81 \[r1\]](https://reviewable.io:443/reviews/m-lab/mlab-wikis/49#-K7wC4AKEwKPe94i2wuW:-K7wC4AKEwKPe94i2wuX:1755335617) ([raw file](https://github.com/m-lab/mlab-wikis/blob/031ca1daedd628b070bd82933645b1d76c765f05/MigratingToFastTables.md#L81)):*
Just a style thing, I'd make this italics and have it be "Note: This does not apply..."

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/mlab-wikis/49)*

**Comment by georgiamoon** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/mlab-wikis/49)*

**Comment by critzo** [comment]
*[MigratingToFastTables.md, line 30 \[r1\]](https://reviewable.io:443/reviews/m-lab/mlab-wikis/49#-K7wKOwftPe_e4Jz83JU:-K7wKOwgC7vrdeNgHSkX:-583559857) ([raw file](https://github.com/m-lab/mlab-wikis/blob/031ca1daedd628b070bd82933645b1d76c765f05/MigratingToFastTables.md#L30)):*
I think the note about the numeric values being UNIX timestamps in seconds should precede the examples, and also would remove the need for the end of line comments (-- 2015-01-01T00:00:00Z). We might also provide an example of using BQ's  SEC_TO_TIMESTAMP() function here as an alternative to using only timestamps.

For example: 
The numeric values in the examples below are UNIX timestamps (in seconds).  

```
WHERE 
   (web100_log_entry.log_time >= 1420070400)     
   AND (web100_log_entry.log_time < 1427846400)) 
```

Big Query also provides a number of date/time formatting functions <link> to convert human-readable dates into timestamps, for example:

```
WHERE 
   (web100_log_entry.log_time >= SEC_TO_TIMESTAMP('2015-01-01') )     
   AND (web100_log_entry.log_time < SEC_TO_TIMESTAMP('2015-04-01') )) 
```
Please note that utilizing BQ functions such as SEC_TO_TIMESTAMP() may also affect the speed of your query.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/mlab-wikis/49)*

**Comment by critzo** [comment]
I had one comment on section 2, but otherwise looks great!

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/mlab-wikis/49#-:-K7wUWJU15cRUqfJMDjy:-140547327)*

**Comment by mtlynch** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[MigratingToFastTables.md, line 30 \[r1\]](https://reviewable.io:443/reviews/m-lab/mlab-wikis/49#-K7wKOwftPe_e4Jz83JU:-K85dQgHIKUANskaYrFo:-720195957) ([raw file](https://github.com/m-lab/mlab-wikis/blob/031ca1daedd628b070bd82933645b1d76c765f05/MigratingToFastTables.md#L30)):*
I really hate using the UNIX timestamp, but I feel like offering both options clutters the example a bit. I've pushed a branch that shows what it looks like here:

https://github.com/mtlynch/mlab-wikis/blob/alternative-time/MigratingToFastTables.md

For now, I've left just the UNIX timestamp example and integrated your feedback about moving up the explanation of the numeric values. Let me know if this works for you.

---

*[MigratingToFastTables.md, line 81 \[r1\]](https://reviewable.io:443/reviews/m-lab/mlab-wikis/49#-K7wC4AKEwKPe94i2wuW:-K80Ri-O8DZ2ZSe776nJ:1154580994) ([raw file](https://github.com/m-lab/mlab-wikis/blob/031ca1daedd628b070bd82933645b1d76c765f05/MigratingToFastTables.md#L81)):*
Fixed, thanks.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/mlab-wikis/49)*

**Comment by critzo** [comment]
*[MigratingToFastTables.md, line 30 \[r1\]](https://reviewable.io:443/reviews/m-lab/mlab-wikis/49#-K7wKOwftPe_e4Jz83JU:-K85g3iwbWI270jwr8XR:480023304) ([raw file](https://github.com/m-lab/mlab-wikis/blob/031ca1daedd628b070bd82933645b1d76c765f05/MigratingToFastTables.md#L30)):*
I agree, it does clutter up the flow a bit. I think a single reference at the end (after the original examples for NDT, NPAD and Sidestream and after the original PT example would be simpler.  So a complete section section 2 would look like this:

## 2. Add a `WHERE` clause to restrict based on test time

If your queries were using the table names as a means of limiting a query to a particular time range, it will be necessary to add `WHERE` clauses to continue enforcing this time range.

For NDT, NPAD, and SideStream, add a query of the following form (where the
numeric values are UNIX timestamps in seconds):

```
WHERE
  (web100_log_entry.log_time >= 1420070400)      -- 2015-01-01T00:00:00Z
   AND (web100_log_entry.log_time < 1427846400)) -- 2015-04-01T00:00:00Z
```

For Paris Traceroute, add a query of the following form (where the numeric
values are UNIX timestamps in seconds):

```
WHERE
  (log_time >= 1420070400)                       -- 2015-01-01T00:00:00Z
   AND (log_time < 1427846400))                  -- 2015-04-01T00:00:00Z
```
### Optional Date/time Formatting Functions 

BigQuery also provides a number of [date/time formatting functions](https://cloud.google.com/bigquery/query-reference?hl=en#datetimefunctions) to convert human-readable dates into timestamps. 

For example for NDT, NPAD or Sidestream queries:

```
WHERE
  (web100_log_entry.log_time >= PARSE_UTC_USEC("2015-01-01 00:00:00") / POW(10, 6))
   AND (web100_log_entry.log_time < PARSE_UTC_USEC("2015-04-01 00:00:00") / POW(10, 6))
```

And for Paris Traceroute queries:

```
WHERE
  (log_time >= PARSE_UTC_USEC("2015-01-01 00:00:00") / POW(10, 6))
   AND (log_time < PARSE_UTC_USEC("2015-04-01 00:00:00") / POW(10, 6))
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/mlab-wikis/49)*

**Comment by mtlynch** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[MigratingToFastTables.md, line 30 \[r1\]](https://reviewable.io:443/reviews/m-lab/mlab-wikis/49#-K7wKOwftPe_e4Jz83JU:-K85k7FTc-pf6-dNN0Nd:551846734) ([raw file](https://github.com/m-lab/mlab-wikis/blob/031ca1daedd628b070bd82933645b1d76c765f05/MigratingToFastTables.md#L30)):*
Updated, thanks!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/mlab-wikis/49)*

**Pull request merged**
